language: go
go:
  - 1.8
  - 1.9
  - master
env:
  global: # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: OOu9Wh9fqyX6UZGfxAgkJRpkUiZemSMyOHWwJiGOvlq9kxQNCsag6t5OTrIzaMX/lKJ6ZnbyjSDPtKbQMbz1NdWz5WHkaqa7s2Qzcl1oDX1lycV/J4zx1BrP3BpTLQxOFWF7geCXMXD0eXsIBjMEhZ2b/NZtmzhNZnfx1n/2/OxIfXBvMW4iw8ahU9PRjaje73K7b431r1rzkP3zeKeCUutPcK3WtQAwSRYYT3DOH99MLYVwTmCFfQtq6YrDUiSukrlWeqf/wUh1Y5UzSLOCNPE5athR1TnTmjCobXjOiVFa2kUzwicakjowaNQSt+FwcPDC/CAXkewKnDKArcrpWqFsk74dCx2U7L8/jpDoR3aM6YMQUJH9viceI2WYbTOnYqmxJ5ixKAGwpvXSpBfGeTh4ykV12B5c6FzjiC4jmULcMrOUsfZd80KJzoUpap3le6p72tQUOz0cabYmdExncOprWgFhXm9rQUjvMKn+UedDg+mFOFMjTG7lq6+r+ovnshbErh621mvTRbEetIRKE/0HNIKxcUZTaNJ2/l3MC3s+A1r4VzKA8w4eK9TWt9oe9qj8z78r11YeXwDFbmT9aa4eSMxzaZT2xPNzgAbeFABaaKdLgLMvOHEv0UFxf+EpHGPfPRF8z7pyQGKB5A6TmKlGF8SUaXeYdTVMAXxT570=
    - secure: OKHQbWGvV7DgOBAXvn3wVd8R9WMXo5324/lQRvGytzSk6HkQ2v8spvy12rDKBDu7MJpSfFxtEMNRQ44pSBekKqKvwiUBXai6QIJwyAlZJ//H5/lTYxAIYR9/W7jTuD1ZI8liSMGXCt+iLR0SEwi4FN/QeUts9JcGfXFywo+9E4sFCHCH2w+JmDU6Vlgb+umKN5T77GuLzPqdjmWmtvNMMXXPKmNNc2ozf0BHovSKJtMAkQHN3oFalJ74IRANHO4SnROS4+/AYg8oUf2lNJBC/4PJ5FinpDqiKIyD8HzEYny5OYG/4V50KcLgnWtF9KoMtj2/vyj6krVhQcmQYTJgqBnwMM6PYMYAr7OYB5TltuOlvDxlE8SqvaEIfdityBW1GLNR5eiXikjQ3fYRjBaxucalJA4g2gJ+0GvsXYe2dxO91mxPVaRZlasTdMU3ND+Jt7OdbJvpFsjqBVJYaPqB81oCMCC7a3VtS26KFKkFbdOlY/xjGisVPe2o+OQkT4h3n420IbdtHu5zB9qbz4jxPzczrhvPLU0XVLuqxvhsbheTOUCT+ehw8TWfy83T75NIfWQR12hmqAt+AwVaqOW8ep+4phDuhLs3WBy4sMYVAht5AQd/eCs+gK8qGvPKQAqfqLivEscr0AGAvE+CKTXIR7TrIPPHd8B0lusU38HWhMY=
addons:
before_install:
  - go get github.com/mattn/goveralls
script:
  - make vendor && $HOME/gopath/bin/goveralls -service=travis-ci -ignore "internal/internal.go,internal/public.pb.go,internal/private.pb.go"
before_deploy:
  - pip install awscli --user `whoami`
deploy:
  - provider: script
    script: make prerelease-upload
    skip_cleanup: true
    on:
      branch: master
notifications:
  slack:
    secure: dGOhPuyJRMENgqooKaoDkg2ZkZndVXMCUyr8eZK2TkUHFBvXTS1ajDYyNbzlokzgHQefD96ZlgAiuE5H/VLUW7fK1CyWsVIgC/BaEbeXquZJN/fwoCx7H5JI6eXHF1ZiBkI6X6TTg3fQ6t1yuBUNYwcUp0RFW3pAsuC7a1Xt4n7jrBaKwesvgZN8Gj6uZFj6cm5ogSBuq0TQxhryFfk9KVuUHGObiFAMtfSFH4K6VdhHnTJNsNeWZ6ekbYMmSaIFcK/Y4YKOagniCa6d5Ztlh0+RjM5j2HnMZWaMLa5y5C5i4QLuNxLVil6ZSfLWCd1U1R5kGuhTUoFSIRCKwOfomOl/eYHDLmUttjbDHHkLYgFwgSS7lOPhfcA+czOuZNf3C7VBLEvW3DfOwcExiVp2Z4dGltBMReF8LIQPIf3/8DA1wTS4slpBeOxFcOMUgpGg2FU5JMkmtUZtEv7vn4ru9y1YESJHARJzDMmBEFyQTbG23otAt1VsHLzOdwKRYROE1DByET7xzhiP03W1n8tSjehg01G4ziHXzHdsJdkQbfMO6il5zCLsvtn2+uH2Lw7fqx6fHJ1+3Yh+poztVliCXdLohw3mCkNShtU/bsyidBqG7sknGYN0BB8QjH4i1XGHBeyNReeJETT2k33FOa5NdfTwiAGmR20iwQAZqjUVRx4=
