# This file intentionally left blank as all needed dependencies are imported by
# the project and thus tracked by `dep`.
# See https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md for details.


[[constraint]]
  # Required: the root import path of the project being constrained.
  name = "github.com/DataDog/datadog-go"
  # Recommended: the version constraint to enforce for the project.
  # Only one of "branch", "version" or "revision" can be specified.
  branch = "master"
